# Generated by Django 4.1.1 on 2023-02-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazorcollection',
            name='unique_key',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
