# Generated by Django 4.1.1 on 2023-03-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mazorcollection_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='desc',
        ),
    ]
