# Generated by Django 4.1.1 on 2023-03-23 12:27

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_notification_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
