# Generated by Django 4.1.1 on 2023-04-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notification_notification'),
        ('superadmin', '0002_manualwithdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualwithdraw',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualwithdraw',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tran', to='core.transtions'),
        ),
    ]
