# Generated by Django 4.1.1 on 2023-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_manualwithdraw_created_alter_manualwithdraw_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualwithdraw',
            name='fund_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manualwithdraw',
            name='fund_ifsc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manualwithdraw',
            name='fund_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
