# Generated by Django 4.1.1 on 2023-05-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='razorpay_contact',
            new_name='unique_key',
        ),
    ]
