# Generated by Django 4.1.1 on 2023-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_account', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=30)),
                ('bank_account', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=30, null=True)),
                ('bankname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
